# **CMSC320 Final Project**
## **Checkpoint 2**
### Group: Jerico Estrella, Tanush Parhi, Ronit Munshi, Jake Glendon, Sang Pham

In [18]:
# import libraries
import pandas as pd
from datetime import datetime
import string

### **Data preprocessing**

#### **Dataset #1**

(a) import

In [19]:
df1 = pd.read_csv("VideoGamesSales-2016.csv")
print(df1.shape)
print(df1.dtypes)
display(df1)

(16719, 16)
Name                object
Platform            object
Year_of_Release    float64
Genre               object
Publisher           object
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count       float64
User_Score          object
User_Count         float64
Developer           object
Rating              object
dtype: object

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

(b) parse

In [20]:
# makes all the string data in lowercase and makes sure any whitespace is removed
df1["Name"] = df1["Name"].str.lower().str.strip()
df1["Platform"] = df1["Platform"].str.lower().str.strip()
df1["Publisher"] = df1["Publisher"].str.lower().str.strip()
df1["Genre"] = df1["Genre"].str.lower().str.strip()
df1["Developer"] = df1["Developer"].str.lower().str.strip()
df1["Rating"] = df1["Rating"].str.lower().str.strip()

display(df1)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,wii sports,wii,2006.0,sports,nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,nintendo,e
1,super mario bros.,nes,1985.0,platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,mario kart wii,wii,2008.0,racing,nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,nintendo,e
3,wii sports resort,wii,2009.0,sports,nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,nintendo,e
4,pokemon red/pokemon blue,gb,1996.0,role-playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,samurai warriors: sanada maru,ps3,2016.0,action,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,lma manager 2007,x360,2006.0,sports,codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,haitaka no psychedelica,psv,2016.0,adventure,idea factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,spirits & spells,gba,2003.0,platform,wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,winning post 8 2016,psv,2016.0,simulation,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# drops any sales that are NULL
df1 = df1.dropna(subset=["Global_Sales"])
# drops any duplucaite row entries
df1 = df1.drop_duplicates()
# only used rows where total sales greater than 0
df1 = df1[df1["Global_Sales"] > 0]

print(df1.shape)
display(df1)

(16719, 16)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,wii sports,wii,2006.0,sports,nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,nintendo,e
1,super mario bros.,nes,1985.0,platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,mario kart wii,wii,2008.0,racing,nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,nintendo,e
3,wii sports resort,wii,2009.0,sports,nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,nintendo,e
4,pokemon red/pokemon blue,gb,1996.0,role-playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,samurai warriors: sanada maru,ps3,2016.0,action,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,lma manager 2007,x360,2006.0,sports,codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,haitaka no psychedelica,psv,2016.0,adventure,idea factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,spirits & spells,gba,2003.0,platform,wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,winning post 8 2016,psv,2016.0,simulation,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# converts the year column to Int64 integers from floats, with any NaNs becoming nullable ints
df1["Year_of_Release"] = pd.to_numeric(df1['Year_of_Release'], errors='coerce').astype('Int64')
# makes sure that the user score stays in its numeric float64 types
df1["User_Score"] = pd.to_numeric(df1['User_Score'], errors='coerce')

print(df1.dtypes)
display(df1)

Name                object
Platform            object
Year_of_Release      Int64
Genre               object
Publisher           object
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count       float64
User_Score         float64
User_Count         float64
Developer           object
Rating              object
dtype: object

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,wii sports,wii,2006,sports,nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,nintendo,e
1,super mario bros.,nes,1985,platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,mario kart wii,wii,2008,racing,nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,nintendo,e
3,wii sports resort,wii,2009,sports,nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,nintendo,e
4,pokemon red/pokemon blue,gb,1996,role-playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,samurai warriors: sanada maru,ps3,2016,action,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,lma manager 2007,x360,2006,sports,codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,haitaka no psychedelica,psv,2016,adventure,idea factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,spirits & spells,gba,2003,platform,wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,winning post 8 2016,psv,2016,simulation,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# makes sure that the Critic_Score stays in its numeric float64 types
df1['Critic_Score'] = pd.to_numeric(df1['Critic_Score'], errors='coerce')

# Converts the critics_count and user-count columns to Int64 since they are whole numbers
# with any NaNs being converted to nullable integers
df1['Critic_Count'] = pd.to_numeric(df1['Critic_Count'], errors='coerce').astype('Int64')
df1['User_Count'] = pd.to_numeric(df1['User_Count'], errors='coerce').astype('Int64')

# makes sure the sales data is still in the form of float64 decimals
df1['JP_Sales'] = pd.to_numeric(df1['JP_Sales'], errors='coerce')
df1['NA_Sales'] = pd.to_numeric(df1['NA_Sales'], errors='coerce')
df1['EU_Sales'] = pd.to_numeric(df1['EU_Sales'], errors='coerce')
df1['Other_Sales'] = pd.to_numeric(df1['Other_Sales'], errors='coerce')
df1['Global_Sales'] = pd.to_numeric(df1['Global_Sales'], errors='coerce')

print(df1.dtypes)
display(df1)

Name                object
Platform            object
Year_of_Release      Int64
Genre               object
Publisher           object
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count         Int64
User_Score         float64
User_Count           Int64
Developer           object
Rating              object
dtype: object

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,wii sports,wii,2006,sports,nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51,8.0,322,nintendo,e
1,super mario bros.,nes,1985,platform,nintendo,29.08,3.58,6.81,0.77,40.24,NaN,<NA>,NaN,<NA>,NaN,NaN
2,mario kart wii,wii,2008,racing,nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73,8.3,709,nintendo,e
3,wii sports resort,wii,2009,sports,nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73,8.0,192,nintendo,e
4,pokemon red/pokemon blue,gb,1996,role-playing,nintendo,11.27,8.89,10.22,1.00,31.37,NaN,<NA>,NaN,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,samurai warriors: sanada maru,ps3,2016,action,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,<NA>,NaN,<NA>,NaN,NaN
16715,lma manager 2007,x360,2006,sports,codemasters,0.00,0.01,0.00,0.00,0.01,NaN,<NA>,NaN,<NA>,NaN,NaN
16716,haitaka no psychedelica,psv,2016,adventure,idea factory,0.00,0.00,0.01,0.00,0.01,NaN,<NA>,NaN,<NA>,NaN,NaN
16717,spirits & spells,gba,2003,platform,wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,<NA>,NaN,<NA>,NaN,NaN
16718,winning post 8 2016,psv,2016,simulation,tecmo koei,0.00,0.00,0.01,0.00,0.01,NaN,<NA>,NaN,<NA>,NaN,NaN

In [24]:
# cheecks if anu of the sales data has any nulls by suming up the total
# nulls in each column
sales_cols = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

df1[sales_cols].isnull().sum()

NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

(c) organize

In [25]:
# extracts all the common columns between this dataset and the second dataset below
df1 = df1[["Name", "Publisher", "Platform", "Genre", "Year_of_Release", "Global_Sales", "NA_Sales", "JP_Sales", "EU_Sales", "Other_Sales", "Critic_Score"]]

# makes all the column names lowercase and makes Name match the second dataset's name
renaming_scheme = {
    'Name': 'game_name',
    'Platform': 'platform',
    'Genre': 'genre',
    'Publisher': 'publisher',
    'Developer': 'developer',
    'Critic_Score': 'critic_score',
    'Global_Sales': 'total_sales',
    'NA_Sales': 'na_sales',
    'JP_Sales': 'jp_sales',
    'EU_Sales': 'eu_sales',
    'Other_Sales': 'other_sales',
}

# renames all the columns according to the renaming scheme
df1 = df1.rename(columns=renaming_scheme)

print(df1.dtypes)
display(df1)

game_name           object
publisher           object
platform            object
genre               object
Year_of_Release      Int64
total_sales        float64
na_sales           float64
jp_sales           float64
eu_sales           float64
other_sales        float64
critic_score       float64
dtype: object

,game_name,publisher,platform,genre,Year_of_Release,total_sales,na_sales,jp_sales,eu_sales,other_sales,critic_score
0,wii sports,nintendo,wii,sports,2006,82.53,41.36,3.77,28.96,8.45,76.0
1,super mario bros.,nintendo,nes,platform,1985,40.24,29.08,6.81,3.58,0.77,NaN
2,mario kart wii,nintendo,wii,racing,2008,35.52,15.68,3.79,12.76,3.29,82.0
3,wii sports resort,nintendo,wii,sports,2009,32.77,15.61,3.28,10.93,2.95,80.0
4,pokemon red/pokemon blue,nintendo,gb,role-playing,1996,31.37,11.27,10.22,8.89,1.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16714,samurai warriors: sanada maru,tecmo koei,ps3,action,2016,0.01,0.00,0.01,0.00,0.00,NaN
16715,lma manager 2007,codemasters,x360,sports,2006,0.01,0.00,0.00,0.01,0.00,NaN
16716,haitaka no psychedelica,idea factory,psv,adventure,2016,0.01,0.00,0.01,0.00,0.00,NaN
16717,spirits & spells,wanadoo,gba,platform,2003,0.01,0.01,0.00,0.00,0.00,NaN
16718,winning post 8 2016,tecmo koei,psv,simulation,2016,0.01,0.00,0.01,0.00,0.00,NaN

#### **Dataset #2**

(a) import

(b) parse

(c) organize

**Combining/Merging Datasets**

### **Basic data exploration and summary statistics**

- Conclusion #1:

- Conclusion #2:

- Conclusion #3: